# Generated by Django 5.0.8 on 2024-08-22 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_delete_stockdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DecimalField(decimal_places=2, max_digits=6)),
                ('openPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('highPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lowPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('closePrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
        ),
    ]
