# Generated by Django 5.0.8 on 2024-08-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_assethistory_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tunnelType',
            field=models.TextField(null=True),
        ),
    ]
